spring:
  liquibase:
    change-log: classpath*:/db-migrations/db-changelog.xml

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/company
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: false

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
